#!/bin/bash


## Load the required modules
module load mpt
module load gcc

## compile


## compile with MPI:
mpicxx 2DWave_parallel.cpp  -o waveExe

## remove object files if there is any!:
# rm *.mod
# rm *.o

